# Generated by Django 3.2.19 on 2023-06-28 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ім`я кліента:')),
                ('surname', models.CharField(max_length=100, verbose_name='Призвісько кліента:')),
                ('gmail', models.CharField(max_length=200, verbose_name='Електронна скринька кліента:')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
